version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "${PASSWORD}"
      POSTGRES_USER: "${USERNAME}"
      POSTGRES_DB: "${DBNAME}"
    ports:
      - "127.0.0.1:5432:5432"
  web-app:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
